
import { Language } from './types';

export const calculateDistance = (lat1: number, lon1: number, lat2: number, lon2: number): number => {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const d = R * c;
  return Math.round(d * 10) / 10;
};

export const TRANSLATIONS: Record<string, any> = {
  English: {
    welcome: "Welcome to AgriConnect",
    selectRole: "Please select your role to continue",
    farmer: "Farmer",
    worker: "Agricultural Worker",
    provider: "Equipment Provider",
    store: "Agri Input Store",
    farmerDesc: "Post farm jobs, find skilled workers, and rent modern machinery.",
    workerDesc: "Find nearby farm work, earn daily wages, and build your profile.",
    providerDesc: "List your tractors and tools to earn extra income by renting.",
    storeDesc: "Sell seeds, fertilizers, and pesticides to local farmers.",
    detecting: "Detecting location...",
    location: "Your Location",
    change: "Change",
    workers: "Find Workers",
    equipment: "Rent Machinery",
    stores: "Agri Stores",
    farmers: "Farmers Nearby",
    nearest: "Nearest to me",
    rating: "Best Rated",
    km: "km away",
    call: "Call Now",
    book: "Book Service",
    perDay: "/day",
    noResults: "No results found in this area. Try expanding your search.",
    expand: "Expand Search",
    loginTitle: "Welcome Back",
    signupTitle: "Create New Account",
    fullName: "Your Full Name",
    phoneNumber: "Mobile Number",
    enterName: "Enter your full name",
    getOtp: "Get Verification Code",
    verifyOtp: "Verify and Login",
    otpSent: "Verification code sent to",
    resendOtp: "Didn't get code? Resend",
    postJob: "Post a New Job",
    myJobs: "My Job Postings",
    dailyWage: "Daily Wage",
    workType: "Type of Work",
    description: "Work Details",
    available: "I am Available",
    notAvailable: "Currently Busy",
    fleet: "My Equipment Fleet",
    addEquip: "Add New Machinery",
    rentals: "Active Rentals",
    statusOpen: "OPEN",
    statusFilled: "FILLED",
    statusCompleted: "COMPLETED",
    statusCancelled: "CANCELLED",
    manageJobs: "Manage Your Job Postings",
    findJobs: "Find Jobs",
    availableWork: "Available Work",
    loading: "Loading...",
    myStore: "My Store Profile",
    products: "Products List",
    addProduct: "Add Product",
    shopName: "Shop Name",
    seeds: "Seeds",
    fertilizers: "Fertilizers",
    pesticides: "Pesticides",
    tools: "Tools"
  },
  Hindi: {
    welcome: "एग्रीकनेक्ट में आपका स्वागत है",
    selectRole: "आगे बढ़ने के लिए अपनी भूमिका चुनें",
    farmer: "किसान भाई",
    worker: "खेती मजदूर",
    provider: "उपकरण प्रदाता",
    store: "कृषि इनपुट स्टोर",
    farmerDesc: "खेती के काम डालें, कुशल मजदूर खोजें और आधुनिक मशीनें किराए पर लें।",
    workerDesc: "पास में खेती का काम ढूंढें, दैनिक मजदूरी कमाएं और अपनी पहचान बनाएं।",
    providerDesc: "अतिरिक्त आय के लिए अपने ट्रैक्टर और औजार किराए पर दें।",
    storeDesc: "स्थानीय किसानों को बीज, उर्वरक और कीटनाशक बेचें।",
    detecting: "स्थान खोज रहे हैं...",
    location: "आपका स्थान",
    change: "बदलें",
    workers: "मजदूर खोजें",
    equipment: "मशीनें किराए पर लें",
    stores: "कृषि दुकानें",
    farmers: "आस-पास के किसान",
    nearest: "मेरे सबसे पास",
    rating: "सबसे अच्छी रेटिंग",
    km: "किमी दूर",
    call: "अभी कॉल करें",
    book: "बुकिंग करें",
    perDay: "/दिन",
    noResults: "इस क्षेत्र में कोई परिणाम नहीं मिला। अपनी खोज का दायरा बढ़ाएं।",
    expand: "खोज बढ़ाएं",
    loginTitle: "आपका स्वागत है",
    signupTitle: "नया खाता बनाएँ",
    fullName: "आपका पूरा नाम",
    phoneNumber: "मोबाइल नंबर",
    enterName: "अपना पूरा नाम लिखें",
    getOtp: "ओटीपी प्राप्त करें",
    verifyOtp: "ओटीपी सत्यापित करें",
    otpSent: "सत्यापन कोड इस नंबर पर भेजा गया:",
    resendOtp: "कोड नहीं मिला? दोबारा भेजें",
    postJob: "नया काम डालें",
    myJobs: "मेरे द्वारा डाले गए काम",
    dailyWage: "दैनिक मजदूरी",
    workType: "काम का प्रकार",
    description: "काम का विवरण",
    available: "मैं काम के लिए उपलब्ध हूँ",
    notAvailable: "अभी व्यस्त हूँ",
    fleet: "मेरी मशीनें",
    addEquip: "नई मशीन जोड़ें",
    rentals: "सक्रिय किराये",
    statusOpen: "खुला है",
    statusFilled: "भरा हुआ",
    statusCompleted: "पूरा हुआ",
    statusCancelled: "रद्द",
    manageJobs: "अपने डाले गए कामों को प्रबंधित करें",
    findJobs: "काम ढूंढें",
    availableWork: "उपलब्ध काम",
    loading: "लोड हो रहा है...",
    myStore: "मेरी दुकान",
    products: "उत्पादों की सूची",
    addProduct: "उत्पाद जोड़ें",
    shopName: "दुकान का नाम",
    seeds: "बीज",
    fertilizers: "उर्वरक",
    pesticides: "कीटनाशक",
    tools: "औजार"
  },
  Telugu: {
    welcome: "AgriConnect కి స్వాగతం",
    selectRole: "కొనసాగడానికి మీ పాత్రను ఎంచుకోండి",
    farmer: "రైతు సోదరులు",
    worker: "వ్యవసాయ కూలీ",
    provider: "యంత్రాల ప్రదాత",
    store: "వ్యవసాయ దుకాణం",
    farmerDesc: "పనులు పోస్ట్ చేయండి, నైపుణ్యం గల కూలీలను మరియు యంత్రాలను అద్దెకు తీసుకోండి.",
    workerDesc: "దగ్గర్లో పనులు వెతుక్కోండి, రోజువారీ కూలీ సంపాదించండి మరియు గుర్తింపు పొందండి.",
    providerDesc: "మీ ట్రాక్టర్లు మరియు పనిముట్లను అద్దెకు ఇచ్చి అదనపు ఆదాయం పొందండి.",
    storeDesc: "స్థానిక రైతులకు విత్తనాలు, ఎరువులు మరియు పురుగుమందులను అమ్మండి.",
    detecting: "ప్రాంతాన్ని గుర్తిస్తోంది...",
    location: "మీ ప్రాంతం",
    change: "మార్చు",
    workers: "కూలీల కోసం",
    equipment: "యంత్రాల అద్దెకు",
    stores: "వ్యవసాయ షాపులు",
    farmers: "దగ్గర్లో ఉన్న రైతులు",
    nearest: "అన్నిటికంటే దగ్గరివి",
    rating: "మంచి రేటింగ్ ఉన్నవి",
    km: "కి.మీ దూరంలో",
    call: "కాల్ చేయండి",
    book: "బుక్ చేయండి",
    perDay: "/రోజుకు",
    noResults: "ఈ ప్రాంతంలో ఏమీ కనిపించలేదు. మీ శోధన పరిధిని పెంచండి.",
    expand: "పరిధి పెంచండి",
    loginTitle: "స్వాగతం",
    signupTitle: "కొత్త ఖాతా తెరవండి",
    fullName: "మీ పూర్తి పేరు",
    phoneNumber: "మొబైల్ సంఖ్య",
    enterName: "మీ పూర్తి పేరు నమోదు చేయండి",
    getOtp: "ఓటిపి పొందండి",
    verifyOtp: "ఓటిపిని నిర్ధారించండి",
    otpSent: "ధృవీకరణ కోడ్ పంపబడిన సంఖ్య:",
    resendOtp: "కోడ్ రాలేదా? మళ్ళీ పంపండి",
    postJob: "కొత్త పనిని నమోదు చేయండి",
    myJobs: "నేను పెట్టిన పనులు",
    dailyWage: "రోజువారీ కూలీ",
    workType: "పని రకం",
    description: "పని వివరాలు",
    available: "నేను అందుబాటులో ఉన్నాను",
    notAvailable: "ప్రస్తుతం బిజీగా ఉన్నాను",
    fleet: "నా యంత్రాలు",
    addEquip: "కొత్త యంత్రాన్ని చేర్చండి",
    rentals: "అద్దెకు ఉన్నవి",
    statusOpen: "ఖాళీగా ఉంది",
    statusFilled: "నిండిపోయింది",
    statusCompleted: "పూర్తయింది",
    statusCancelled: "రద్దు చేయబడింది",
    manageJobs: "మీరు పెట్టిన పనులను నిర్వహించండి",
    findJobs: "పనులను వెతకండి",
    availableWork: "అందుబాటులో ఉన్న పనులు",
    loading: "లోడ్ అవుతోంది...",
    myStore: "నా దుకాణం",
    products: "వస్తువుల జాబితా",
    addProduct: "వస్తువును చేర్చు",
    shopName: "షాపు పేరు",
    seeds: "విత్తనాలు",
    fertilizers: "ఎరువులు",
    pesticides: "పురుగుమందులు",
    tools: "పనిముట్లు"
  },
  Tamil: {
    welcome: "AgriConnect-க்கு வரவேற்கிறோம்",
    selectRole: "தொடர உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்",
    farmer: "விவசாயி",
    worker: "விவசாயத் தொழிலாளி",
    provider: "உபகரண வழங்குநர்",
    store: "விவசாய உள்ளீட்டு கடை",
    farmerDesc: "வேலைகளைப் பதிவு செய்யுங்கள், திறமையான தொழிலாளர்களைக் கண்டறியுங்கள்.",
    workerDesc: "அருகிலுள்ள பண்ணை வேலையைக் கண்டுபிடிங்கள், தினசரி கூலி சம்பாதியுங்கள்.",
    providerDesc: "கூடுதல் வருமானம் ஈட்ட உங்கள் டிராக்டர்களை வாடகைக்கு விடுங்கள்.",
    storeDesc: "உள்ளூர் விவசாயிகளுக்கு விதைகள் மற்றும் உரங்களை விற்பனை செய்யுங்கள்.",
    detecting: "இடத்தைக் கண்டறிகிறது...",
    location: "உங்கள் இடம்",
    change: "மாற்று",
    workers: "தொழிலாளர்கள்",
    equipment: "இயந்திரங்கள்",
    stores: "விவசாயக் கடைகள்",
    farmers: "அருகிலுள்ள விவசாயிகள்",
    nearest: "எனக்கு அருகில்",
    rating: "சிறந்த மதிப்பீடு",
    km: "கிமீ தொலைவில்",
    call: "இப்போது அழைக்கவும்",
    book: "முன்பதிவு செய்",
    perDay: "/நாள்",
    noResults: "இந்தப் பகுதியில் முடிவுகள் எதுவும் இல்லை.",
    expand: "தேடலை விரிவுபடுத்து",
    loginTitle: "மீண்டும் வருக",
    signupTitle: "புதிய கணக்கை உருவாக்கு",
    fullName: "முழு பெயர்",
    phoneNumber: "கைபேசி எண்",
    enterName: "உங்கள் முழு பெயரை உள்ளிடவும்",
    getOtp: "குறியீட்டைப் பெறு",
    verifyOtp: "சரிபார் மற்றும் உள்நுழை",
    otpSent: "சரிபார்ப்புக் குறியீடு அனுப்பப்பட்டது:",
    resendOtp: "குறியீடு வரவில்லையா? மீண்டும் அனுப்பு",
    postJob: "புதிய வேலையைப் பதிவு செய்",
    myJobs: "எனது பதிவுகள்",
    dailyWage: "தினசரி கூலி",
    workType: "வேலை வகை",
    description: "வேலை விவரங்கள்",
    available: "நான் தயார்",
    notAvailable: "தற்போது வேலையில்",
    fleet: "எனது இயந்திரங்கள்",
    addEquip: "புதிய இயந்திரத்தைச் சேர்",
    rentals: "செயலில் உள்ள வாடகைகள்",
    statusOpen: "திறந்திருக்கும்",
    statusFilled: "நிரப்பப்பட்டது",
    statusCompleted: "முடிந்தது",
    statusCancelled: "ரத்து செய்யப்பட்டது",
    manageJobs: "வேலைகளை நிர்வகி",
    findJobs: "வேலை தேடு",
    availableWork: "கிடைக்கும் வேலை",
    loading: "ஏற்றப்படுகிறது...",
    myStore: "எனது கடை",
    products: "தயாரிப்பு பட்டியல்",
    addProduct: "தயாரிப்பைச் சேர்",
    shopName: "கடை பெயர்",
    seeds: "விதைகள்",
    fertilizers: "உரங்கள்",
    pesticides: "பூச்சிக்கொல்லிகள்",
    tools: "கருவிகள்"
  },
  Kannada: {
    welcome: "AgriConnect ಗೆ ಸ್ವಾಗತ",
    selectRole: "ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ",
    farmer: "ರೈತರು",
    worker: "ಕೃಷಿ ಕಾರ್ಮಿಕರು",
    provider: "ಉಪಕರಣ ಒದಗಿಸುವವರು",
    store: "ಕೃಷಿ ಸ್ಟೋರ್",
    farmerDesc: "ಕೆಲಸಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ, ಕಾರ್ಮಿಕರನ್ನು ಹುಡುಕಿ ಮತ್ತು ಯಂತ್ರಗಳನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.",
    workerDesc: "ಹತ್ತಿರದ ಕೃಷಿ ಕೆಲಸವನ್ನು ಹುಡುಕಿ ಮತ್ತು ದಿನಗೂಲಿ ಗಳಿಸಿ.",
    providerDesc: "ನಿಮ್ಮ ಟ್ರ್ಯಾಕ್ಟರ್‌ಗಳನ್ನು ಬಾಡಿಗೆಗೆ ನೀಡಿ ಹೆಚ್ಚುವರಿ ಆದಾಯ ಗಳಿಸಿ.",
    storeDesc: "ರೈತರಿಗೆ ಬೀಜಗಳು ಮತ್ತು ಗೊಬ್ಬರಗಳನ್ನು ಮಾರಾಟ ಮಾಡಿ.",
    detecting: "ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...",
    location: "ನಿಮ್ಮ ಸ್ಥಳ",
    change: "ಬದಲಿಸಿ",
    workers: "ಕಾರ್ಮಿಕರು",
    equipment: "ಯಂತ್ರೋಪಕರಣ",
    stores: "ಕೃಷಿ ಅಂಗಡಿಗಳು",
    farmers: "ಹತ್ತಿರದ ರೈತರು",
    nearest: "ನನ್ನ ಹತ್ತಿರದ",
    rating: "ಉತ್ತಮ ರೇಟಿಂಗ್",
    km: "ಕಿಮೀ ದೂರ",
    call: "ಈಗ ಕರೆ ಮಾಡಿ",
    book: "ಬುಕ್ ಮಾಡಿ",
    perDay: "/ದಿನ",
    noResults: "ಈ ಪ್ರದೇಶದಲ್ಲಿ ಯಾವುದೇ ಫಲಿತಾಂಶಗಳಿಲ್ಲ.",
    expand: "ಹುಡುಕಾಟ ವಿಸ್ತರಿಸಿ",
    loginTitle: "ಮತ್ತೆ ಸ್ವಾಗತ",
    signupTitle: "ಹೊಸ ಖಾತೆ ತೆರೆಯಿರಿ",
    fullName: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು",
    phoneNumber: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    enterName: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    getOtp: "ಕೋಡ್ ಪಡೆಯಿರಿ",
    verifyOtp: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಆಗಿ",
    otpSent: "ಕೋಡ್ ಕಳುಹಿಸಲಾದ ಸಂಖ್ಯೆ:",
    resendOtp: "ಕೋಡ್ ಬಂದಿಲ್ಲವೇ? ಮರುಕಳುಹಿಸಿ",
    postJob: "ಹೊಸ ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ",
    myJobs: "ನನ್ನ ಪೋಸ್ಟ್‌ಗಳು",
    dailyWage: "ದಿನಗೂಲಿ",
    workType: "ಕೆಲಸದ ವಿಧ",
    description: "ಕೆಲಸದ ವಿವರಗಳು",
    available: "ನಾನು ಲಭ್ಯವಿದ್ದೇನೆ",
    notAvailable: "ಈಗ ಕಾರ್ಯನಿರತ",
    fleet: "ನನ್ನ ಯಂತ್ರಗಳು",
    addEquip: "ಹೊಸ ಯಂತ್ರ ಸೇರಿಸಿ",
    rentals: "ಸಕ್ರಿಯ ಬಾಡಿಗೆಗಳು",
    statusOpen: "ಲಭ್ಯವಿದೆ",
    statusFilled: "ಭರ್ತಿಯಾಗಿದೆ",
    statusCompleted: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    statusCancelled: "ರದ್ದಾಗಿದೆ",
    manageJobs: "ಕೆಲಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    findJobs: "ಕೆಲಸ ಹುಡುಕಿ",
    availableWork: "ಲಭ್ಯವಿರುವ ಕೆಲಸ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    myStore: "ನನ್ನ ಅಂಗಡಿ",
    products: "ಉತ್ಪನ್ನಗಳ ಪಟ್ಟಿ",
    addProduct: "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
    shopName: "ಅಂಗಡಿಯ ಹೆಸರು",
    seeds: "ಬೀಜಗಳು",
    fertilizers: "ಗೊಬ್ಬರಗಳು",
    pesticides: "ಕೀಟನಾಶಕಗಳು",
    tools: "ಪರಿಕರಗಳು"
  },
  Malayalam: {
    welcome: "AgriConnect-ലേക്ക് സ്വാഗതം",
    selectRole: "തുടരുന്നതിന് നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക",
    farmer: "കർഷകൻ",
    worker: "കാർഷിക തൊഴിലാളി",
    provider: "ഉപകരണ ദാതാവ്",
    store: "അഗ്രി സ്റ്റോർ",
    farmerDesc: "ജോലികൾ പോസ്റ്റ് ചെയ്യുക, തൊഴിലാളികളെ കണ്ടെത്തുക, യന്ത്രങ്ങൾ വാടകയ്ക്കെടുക്കുക.",
    workerDesc: "കാർഷിക ജോലികൾ കണ്ടെത്തുക, ദിവസക്കൂലി സമ്പാദിക്കുക.",
    providerDesc: "യന്ത്രങ്ങൾ വാടകയ്ക്ക് നൽകി അധിക വരുമാനം നേടുക.",
    storeDesc: "വിത്തുകളും വളങ്ങളും പ്രാദേശിക കർഷകർക്ക് വിൽക്കുക.",
    detecting: "സ്ഥലം കണ്ടെത്തുന്നു...",
    location: "നിങ്ങളുടെ സ്ഥലം",
    change: "മാറ്റുക",
    workers: "തൊഴിലാളികൾ",
    equipment: "യന്ത്രങ്ങൾ",
    stores: "കൃഷി കടകൾ",
    farmers: "അടുത്തുള്ള കർഷകർ",
    nearest: "ഏറ്റവും അടുത്തുള്ളത്",
    rating: "മികച്ച റേറ്റിംഗ്",
    km: "കിമീ അകലെ",
    call: "വിളിക്കുക",
    book: "ബുക്ക് ചെയ്യുക",
    perDay: "/ദിവസം",
    noResults: "ഈ പ്രദേശത്ത് ഫലങ്ങളൊന്നുമില്ല.",
    expand: "തിരച്ചിൽ വിപുലീകരിക്കുക",
    loginTitle: "വീണ്ടും സ്വാഗതം",
    signupTitle: "പുതിയ അക്കൗണ്ട് ഉണ്ടാക്കുക",
    fullName: "പൂർണ്ണമായ പേര്",
    phoneNumber: "മൊബൈൽ നമ്പർ",
    enterName: "നിങ്ങളുടെ പേര് നൽകുക",
    getOtp: "കോഡ് ലഭിക്കുക",
    verifyOtp: "പരിശോധിച്ചു ലോഗിൻ ചെയ്യുക",
    otpSent: "കോഡ് അയച്ച നമ്പർ:",
    resendOtp: "കോഡ് ലഭിച്ചില്ലേ? വീണ്ടും അയക്കുക",
    postJob: "പുതിയ ജോലി പോസ്റ്റ് ചെയ്യുക",
    myJobs: "എന്റെ പോസ്റ്റുകൾ",
    dailyWage: "ദിവസക്കൂലി",
    workType: "ജോലിയുടെ തരം",
    description: "ജോലി വിവരങ്ങൾ",
    available: "ലഭ്യമാണ്",
    notAvailable: "തിരക്കിലാണ്",
    fleet: "എന്റെ യന്ത്രങ്ങൾ",
    addEquip: "പുതിയ യന്ത്രം ചേർക്കുക",
    rentals: "വാടകയ്ക്കുള്ളവ",
    statusOpen: "തുറന്നതാണ്",
    statusFilled: "പൂർത്തിയായി",
    statusCompleted: "പൂർത്തിയായി",
    statusCancelled: "റദ്ദാക്കി",
    manageJobs: "ജോലികൾ നിയന്ത്രിക്കുക",
    findJobs: "ജോലി കണ്ടെത്തുക",
    availableWork: "ജോലി ലഭ്യമാണ്",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    myStore: "എന്റെ കട",
    products: "ഉൽപ്പന്ന പട്ടിക",
    addProduct: "ഉൽപ്പന്നം ചേർക്കുക",
    shopName: "കടയുടെ പേര്",
    seeds: "വിത്തുകൾ",
    fertilizers: "വളങ്ങൾ",
    pesticides: "കീടനാശിനികൾ",
    tools: "ഉപകരണങ്ങൾ"
  },
  Marathi: {
    welcome: "AgriConnect मध्ये स्वागत आहे",
    selectRole: "पुढे जाण्यासाठी तुमची भूमिका निवडा",
    farmer: "शेतकरी",
    worker: "शेतमजूर",
    provider: "उपकरण प्रदाता",
    store: "कृषी दुकान",
    farmerDesc: "कामे पोस्ट करा, मजूर शोधा आणि यंत्रे भाड्याने घ्या.",
    workerDesc: "जवळपासचे काम शोधा आणि रोजंदारी मिळवा.",
    providerDesc: "तुमचे ट्रॅक्टर भाड्याने देऊन अतिरिक्त उत्पन्न मिळवा.",
    storeDesc: "बी-बियाणे आणि खते स्थानिक शेतकऱ्यांना विका.",
    detecting: "स्थान शोधत आहे...",
    location: "तुमचे स्थान",
    change: "बदला",
    workers: "मजूर शोधा",
    equipment: "यंत्रे",
    stores: "कृषी दुकाने",
    farmers: "जवळपासचे शेतकरी",
    nearest: "माझ्या जवळचे",
    rating: "उत्तम रेटिंग",
    km: "किमी दूर",
    call: "आत्ता कॉल करा",
    book: "बुकिंग करा",
    perDay: "/दिवस",
    noResults: "या क्षेत्रात काहीही सापडले नाही.",
    expand: "शोध वाढवा",
    loginTitle: "स्वागत आहे",
    signupTitle: "नवीन खाते तयार करा",
    fullName: "तुमचे पूर्ण नाव",
    phoneNumber: "मोबाईल नंबर",
    enterName: "तुमचे नाव लिहा",
    getOtp: "ओटीपी मिळवा",
    verifyOtp: "ओटीपी तपासा",
    otpSent: "ओटीपी पाठवलेला नंबर:",
    resendOtp: "मिळाला नाही? पुन्हा पाठवा",
    postJob: "नवीन काम टाका",
    myJobs: "माझी कामे",
    dailyWage: "रोजंदारी",
    workType: "कामाचा प्रकार",
    description: "कामाचा तपशील",
    available: "मी उपलब्ध आहे",
    notAvailable: "सध्या व्यस्त",
    fleet: "माझी यंत्रे",
    addEquip: "नवीन यंत्र जोडा",
    rentals: "सक्रिय भाडे",
    statusOpen: "उघडलेले",
    statusFilled: "भरलेले",
    statusCompleted: "पूर्ण झालेले",
    statusCancelled: "रद्द केलेले",
    manageJobs: "कामे व्यवस्थापित करा",
    findJobs: "काम शोधा",
    availableWork: "उपलब्ध काम",
    loading: "लोड होत आहे...",
    myStore: "माझे दुकान",
    products: "उत्पादनांची यादी",
    addProduct: "उत्पादन जोडा",
    shopName: "दुकानाचे नाव",
    seeds: "बियाणे",
    fertilizers: "खते",
    pesticides: "कीटकनाशके",
    tools: "औजारे"
  },
  Bengali: {
    welcome: "AgriConnect-এ স্বাগতম",
    selectRole: "চালিয়ে যেতে আপনার ভূমিকা চয়ন করুন",
    farmer: "কৃষক",
    worker: "কৃষি শ্রমিক",
    provider: "সরঞ্জাম সরবরাহকারী",
    store: "কৃষি দোকান",
    farmerDesc: "কাজের বিজ্ঞাপন দিন, শ্রমিক খুঁজুন এবং যন্ত্র ভাড়া নিন।",
    workerDesc: "কাছাকাছি কাজ খুঁজুন এবং দৈনিক মজুরি পান।",
    providerDesc: "যন্ত্রপাতি ভাড়া দিয়ে অতিরিক্ত আয় করুন।",
    storeDesc: "বীজ এবং সার স্থানীয় কৃষকদের কাছে বিক্রি করুন।",
    detecting: "অবস্থান খুঁজছে...",
    location: "আপনার অবস্থান",
    change: "পরিবর্তন",
    workers: "শ্রমিক খুঁজুন",
    equipment: "যন্ত্রপাতি",
    stores: "কৃষি দোকান",
    farmers: "কাছাকাছি কৃষক",
    nearest: "আমার সবথেকে কাছে",
    rating: "সেরা রেটিং",
    km: "কিমি দূরে",
    call: "এখনই কল করুন",
    book: "বুক করুন",
    perDay: "/দিন",
    noResults: "এই এলাকায় কিছু পাওয়া যায়নি।",
    expand: "সার্চ বাড়ান",
    loginTitle: "স্বাগতম",
    signupTitle: "নতুন অ্যাকাউন্ট তৈরি করুন",
    fullName: "আপনার পুরো নাম",
    phoneNumber: "মোবাইল নম্বর",
    enterName: "আপনার নাম লিখুন",
    getOtp: "ওটিপি পান",
    verifyOtp: "ওটিপি যাচাই করুন",
    otpSent: "ওটিপি পাঠানো হয়েছে:",
    resendOtp: "পাননি? আবার পাঠান",
    postJob: "নতুন কাজ দিন",
    myJobs: "আমার কাজগুলো",
    dailyWage: "দৈনিক মজুরি",
    workType: "কাজের ধরন",
    description: "কাজের বিবরণ",
    available: "আমি খালি আছি",
    notAvailable: "ব্যস্ত আছি",
    fleet: "আমার যন্ত্রপাতি",
    addEquip: "নতুন যন্ত্র যোগ করুন",
    rentals: "চলতি ভাড়া",
    statusOpen: "খোলা আছে",
    statusFilled: "ভর্তি",
    statusCompleted: "সম্পন্ন",
    statusCancelled: "বাতিল",
    manageJobs: "কাজ পরিচালনা করুন",
    findJobs: "কাজ খুঁজুন",
    availableWork: "কাজ পাওয়া যাবে",
    loading: "লোড হচ্ছে...",
    myStore: "আমার দোকান",
    products: "পণ্যের তালিকা",
    addProduct: "পণ্য যোগ করুন",
    shopName: "দোকানের নাম",
    seeds: "বীজ",
    fertilizers: "সার",
    pesticides: "কীটনাশক",
    tools: "সরঞ্জাম"
  },
  Gujarati: {
    welcome: "AgriConnect માં સ્વાગત છે",
    selectRole: "આગળ વધવા માટે તમારી ભૂમિકા પસંદ કરો",
    farmer: "ખેડૂત",
    worker: "ખેતમજૂર",
    provider: "સાધન પ્રદાતા",
    store: "કૃષિ સ્ટોર",
    farmerDesc: "કામ મૂકો, મજૂરો શોધો અને મશીનો ભાડે લો.",
    workerDesc: "નજીકમાં કામ શોધો અને રોજિંદી મજૂરી મેળવો.",
    providerDesc: "તમારા ટ્રેક્ટર ભાડે આપીને વધારાની આવક મેળવો.",
    storeDesc: "સ્થાનિક ખેડૂતોને બિયારણ અને ખાતર વેચો.",
    detecting: "સ્થાન શોધી રહ્યું છે...",
    location: "તમારું સ્થાન",
    change: "બદલો",
    workers: "મજૂરો શોધો",
    equipment: "મશીનરી",
    stores: "કૃષિ સ્ટોર્સ",
    farmers: "નજીકના ખેડૂતો",
    nearest: "મારા નજીકના",
    rating: "શ્રેષ્ઠ રેટિંગ",
    km: "કિમી દૂર",
    call: "કોલ કરો",
    book: "બુક કરો",
    perDay: "/દિવસ",
    noResults: "આ વિસ્તારમાં કોઈ પરિણામ મળ્યા નથી.",
    expand: "વધારે શોધો",
    loginTitle: "સ્વાગત છે",
    signupTitle: "નવું ખાતું બનાવો",
    fullName: "તમારું પૂરું નામ",
    phoneNumber: "મોબાઈલ નંબર",
    enterName: "તમારું નામ લખો",
    getOtp: "ઓટીપી મેળવો",
    verifyOtp: "ઓટીપી ચકાસો",
    otpSent: "ઓટીપી મોકલેલો નંબર:",
    resendOtp: "ન મળ્યો? ફરી મોકલો",
    postJob: "નવું કામ મૂકો",
    myJobs: "મારી જાહેરાતો",
    dailyWage: "રોજિંદી મજૂરી",
    workType: "કામનો પ્રકાર",
    description: "કામની વિગત",
    available: "હું ખાલી છું",
    notAvailable: "હમણાં વ્યસ્ત",
    fleet: "મારા સાધનો",
    addEquip: "નવું મશીન ઉમેરો",
    rentals: "ચાલુ ભાડા",
    statusOpen: "ખુલ્લું",
    statusFilled: "ભરાયેલું",
    statusCompleted: "પૂર્ણ",
    statusCancelled: "રદ",
    manageJobs: "કામનું સંચાલન કરો",
    findJobs: "કામ શોધો",
    availableWork: "ઉપલબ્ધ કામ",
    loading: "લોડ થઈ રહ્યું છે...",
    myStore: "મારી દુકાન",
    products: "ઉત્પાદનોની યાદી",
    addProduct: "ઉત્પાદન ઉમેરો",
    shopName: "દુકાનનું નામ",
    seeds: "બિયારણ",
    fertilizers: "ખાતર",
    pesticides: "જંતુનાશક",
    tools: "સાધનો"
  },
  Punjabi: {
    welcome: "AgriConnect ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    selectRole: "ਅੱਗੇ ਵਧਣ ਲਈ ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ",
    farmer: "ਕਿਸਾਨ",
    worker: "ਖੇਤ ਮਜ਼ਦੂਰ",
    provider: "ਮਸ਼ੀਨਰੀ ਪ੍ਰਦਾਤਾ",
    store: "ਖੇਤੀਬਾੜੀ ਸਟੋਰ",
    farmerDesc: "ਕੰਮ ਪੋਸਟ ਕਰੋ, ਮਜ਼ਦੂਰ ਲੱਭੋ ਅਤੇ ਮਸ਼ੀਨਾਂ ਕਿਰਾਏ ਤੇ ਲਓ।",
    workerDesc: "ਨੇੜੇ ਖੇਤੀ ਦਾ ਕੰਮ ਲੱਭੋ ਅਤੇ ਦਿਹਾੜੀ ਕਮਾਓ।",
    providerDesc: "ਟ੍ਰੈਕਟਰ ਕਿਰਾਏ ਤੇ ਦੇ ਕੇ ਵਾਧੂ ਕਮਾਈ ਕਰੋ।",
    storeDesc: "ਸਥਾਨਕ ਕਿਸਾਨਾਂ ਨੂੰ ਬੀਜ ਅਤੇ ਖਾਦਾਂ ਵੇਚੋ।",
    detecting: "ਥਾਂ ਲੱਭ ਰਿਹਾ ਹੈ...",
    location: "ਤੁਹਾਡੀ ਥਾਂ",
    change: "ਬਦਲੋ",
    workers: "ਮਜ਼ਦੂਰ ਲੱਭੋ",
    equipment: "ਮਸ਼ੀਨਰੀ",
    stores: "ਖੇਤੀ ਦੁਕਾਨਾਂ",
    farmers: "ਨੇੜਲੇ ਕਿਸਾਨ",
    nearest: "ਮੇਰੇ ਨੇੜੇ",
    rating: "ਵਧੀਆ ਰੇਟਿੰਗ",
    km: "ਕਿਮੀ ਦੂਰ",
    call: "ਕਾਲ ਕਰੋ",
    book: "ਬੁੱਕ ਕਰੋ",
    perDay: "/ਦਿਨ",
    noResults: "ਇਸ ਇਲਾਕੇ ਵਿੱਚ ਕੁਝ ਨਹੀਂ ਮਿਲਿਆ।",
    expand: "ਹੋਰ ਲੱਭੋ",
    loginTitle: "ਜੀ ਆਇਆਂ ਨੂੰ",
    signupTitle: "ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ",
    fullName: "ਤੁਹਾਡਾ ਪੂਰਾ ਨਾਮ",
    phoneNumber: "ਮੋਬਾਈਲ ਨੰਬਰ",
    enterName: "ਆਪਣਾ ਨਾਮ ਲਿਖੋ",
    getOtp: "ਕੋਡ ਪ੍ਰਾਪਤ ਕਰੋ",
    verifyOtp: "ਕੋਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    otpSent: "ਕੋਡ ਭੇਜਿਆ ਗਿਆ ਹੈ:",
    resendOtp: "ਨਹੀਂ ਮਿਲਿਆ? ਦੁਬਾਰਾ ਭੇਜੋ",
    postJob: "ਨਵਾਂ ਕੰਮ ਪਾਓ",
    myJobs: "ਮੇਰੇ ਕੰਮ",
    dailyWage: "ਦਿਹਾੜੀ",
    workType: "ਕੰਮ ਦੀ ਕਿਸਮ",
    description: "ਕੰਮ ਦਾ ਵੇਰਵਾ",
    available: "ਮੈਂ ਵਿਹਲਾ ਹਾਂ",
    notAvailable: "ਹੁਣੇ ਰੁੱਝਿਆ ਹੋਇਆ",
    fleet: "ਮੇਰੀਆਂ ਮਸ਼ੀਨਾਂ",
    addEquip: "ਨਵੀਂ ਮਸ਼ੀਨ ਪਾਓ",
    rentals: "ਕਿਰਾਏ ਤੇ ਚੱਲ ਰਹੀਆਂ",
    statusOpen: "ਖੁੱਲ੍ਹਾ",
    statusFilled: "ਭਰਿਆ",
    statusCompleted: "ਪੂਰਾ",
    statusCancelled: "ਰੱਦ",
    manageJobs: "ਕੰਮਾਂ ਦਾ ਪ੍ਰਬੰਧ ਕਰੋ",
    findJobs: "ਕੰਮ ਲੱਭੋ",
    availableWork: "ਕੰਮ ਮਿਲ ਸਕਦਾ ਹੈ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    myStore: "ਮੇਰੀ ਦੁਕਾਨ",
    products: "ਸਾਮਾਨ ਦੀ ਲਿਸਟ",
    addProduct: "ਸਾਮਾਨ ਪਾਓ",
    shopName: "ਦੁਕਾਨ ਦਾ ਨਾਂ",
    seeds: "ਬੀਜ",
    fertilizers: "ਖਾਦਾਂ",
    pesticides: "ਕੀੜੇਮਾਰ ਦਵਾਈਆਂ",
    tools: "ਔਜ਼ਾਰ"
  },
  Spanish: {
    welcome: "Bienvenido a AgriConnect",
    selectRole: "Por favor, seleccione su rol para continuar",
    farmer: "Agricultor",
    worker: "Trabajador Agrícola",
    provider: "Proveedor de Equipos",
    store: "Tienda de Insumos",
    farmerDesc: "Publique trabajos agrícolas, encuentre trabajadores y alquile maquinaria moderna.",
    workerDesc: "Encuentre trabajo agrícola cercano, gane salarios diarios y cree su perfil.",
    providerDesc: "Anuncie sus tractores y herramientas para ganar ingresos extras alquilándolos.",
    storeDesc: "Venda semillas, fertilizantes y pesticidas a agricultores locales.",
    detecting: "Detectando ubicación...",
    location: "Su Ubicación",
    change: "Cambiar",
    workers: "Buscar Trabajadores",
    equipment: "Alquilar Maquinaria",
    stores: "Tiendas Agrícolas",
    farmers: "Agricultores Cercanos",
    nearest: "Más cercano a mí",
    rating: "Mejor Valorados",
    km: "km de distancia",
    call: "Llamar Ahora",
    book: "Reservar Servicio",
    perDay: "/día",
    noResults: "No se encontraron resultados en esta zona. Intente ampliar su búsqueda.",
    expand: "Ampliar Búsqueda",
    loginTitle: "Bienvenido de nuevo",
    signupTitle: "Crear Cuenta Nueva",
    fullName: "Su Nombre Completo",
    phoneNumber: "Número de Teléfono",
    enterName: "Ingrese su nombre completo",
    getOtp: "Obtener Código",
    verifyOtp: "Verificar e Iniciar",
    otpSent: "Código de verificación enviado a",
    resendOtp: "¿No recibió el código? Reenviar",
    postJob: "Publicar Trabajo Nuevo",
    myJobs: "Mis Publicaciones",
    dailyWage: "Salario Diario",
    workType: "Tipo de Trabajo",
    description: "Detalles del Trabajo",
    available: "Estoy Disponible",
    notAvailable: "Actualmente Ocupado",
    fleet: "Mi Flota de Equipos",
    addEquip: "Agregar Maquinaria",
    rentals: "Alquileres Activos",
    statusOpen: "ABIERTO",
    statusFilled: "OCUPADO",
    statusCompleted: "COMPLETADO",
    statusCancelled: "CANCELADO",
    manageJobs: "Administrar sus publicaciones de trabajo",
    findJobs: "Buscar Trabajos",
    availableWork: "Trabajo Disponible",
    loading: "Cargando...",
    myStore: "Perfil de mi Tienda",
    products: "Lista de Productos",
    addProduct: "Agregar Producto",
    shopName: "Nombre de la Tienda",
    seeds: "Semillas",
    fertilizers: "Fertilizantes",
    pesticides: "Pesticidas",
    tools: "Herramientas"
  }
};
