
import { Job, WorkerProfile, Equipment, RentalHistory } from './types';

// Haversine formula to calculate distance between two points in km
export const calculateDistance = (lat1: number, lon1: number, lat2: number, lon2: number): number => {
  const R = 6371; // Radius of the earth in km
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const d = R * c; // Distance in km
  return Math.round(d * 10) / 10; // Return rounded to 1 decimal place
};

export const TRANSLATIONS = {
  English: {
    welcome: "Welcome to AgriConnect",
    selectRole: "Select Your Role",
    farmer: "Farmer",
    worker: "Worker",
    provider: "Equipment Provider",
    farmerDesc: "Post jobs, hire workers, and rent equipment.",
    workerDesc: "Find nearby jobs and earn wages.",
    providerDesc: "Rent out your machinery and manage inventory.",
    detecting: "Detecting...",
    location: "Location",
    change: "Change",
    workers: "Workers",
    equipment: "Equipment",
    farmers: "Farmers",
    nearest: "Nearest First",
    rating: "Highest Rating",
    km: "km",
    call: "Call",
    book: "Book",
    perDay: "/day",
    noResults: "No results nearby. Try expanding radius.",
    expand: "Expand Search",
    postJob: "Post a Job",
    myJobs: "My Jobs",
    manageJobs: "Manage Your Job Postings",
    noJobs: "You haven't posted any jobs yet.",
    nearbyUsers: "Nearby Real Users",
    sort: "Sort",
    available: "Available",
    busy: "Busy",
    rented: "Rented",
    callFarmer: "Call Farmer",
    viewOnMap: "View on Map",
    workType: "Work Type",
    dailyWage: "Daily Wage",
    description: "Description",
    postJobBtn: "Post Job",
    findJobs: "Find Jobs",
    iAmAvailable: "I am Available",
    notAvailable: "Not Available",
    myFleet: "My Fleet",
    totalItems: "Total Items",
    activeRentals: "Active Rentals",
    manageEquip: "Manage Equipment",
    aiMaintenance: "AI Maintenance",
    editDetails: "Edit Details",
    addNewEquip: "Add New Equipment",
    equipName: "Equipment Name",
    type: "Type",
    manufacturer: "Manufacturer",
    model: "Model",
    year: "Year of Manufacture",
    generatingImage: "Generating Nano-Banana Image...",
    addAndGenerate: "Add & Generate Image",
    maintenanceTips: "Maintenance Tips",
    gotIt: "Got it",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    loginContinue: "Login to continue as",
    registeringAs: "Registering as",
    fullName: "Full Name",
    phoneNum: "Phone Number",
    cityVillage: "City / Village",
    getOtp: "Get OTP",
    verifyContinue: "Verify & Continue",
    changePhone: "Change Phone Number",
    newUser: "New user?",
    signUpHere: "Sign Up here",
    alreadyAccount: "Already have an account?",
    login: "Login",
    saveChanges: "Save Changes",
    profileUpdated: "Profile Updated!",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    phoneNotRegistered: "Phone number not registered",
    pleaseSignUpFirst: "Please sign up first",
    enterValidPhone: "Please enter a valid 10-digit phone number",
    accountExists: "Account already exists. Please login."
  },
  Hindi: {
    welcome: "एग्रीकनेक्ट में आपका स्वागत है",
    selectRole: "अपनी भूमिका चुनें",
    farmer: "किसान",
    worker: "श्रमिक",
    provider: "उपकरण प्रदाता",
    farmerDesc: "नौकरियां पोस्ट करें, श्रमिकों को काम पर रखें और उपकरण किराए पर लें।",
    workerDesc: "पास की नौकरियां खोजें और वेतन अर्जित करें।",
    providerDesc: "अपनी मशीनरी किराए पर दें और इन्वेंट्री का प्रबंधन करें।",
    detecting: "खोज रहा है...",
    location: "स्थान",
    change: "बदलें",
    workers: "श्रमिक",
    equipment: "उपकरण",
    farmers: "किसान",
    nearest: "सबसे पास",
    rating: "सबसे अच्छी रेटिंग",
    km: "किमी",
    call: "कॉल",
    book: "बुक करें",
    perDay: "/दिन",
    noResults: "कोई परिणाम नहीं। दायरा बढ़ाएं।",
    expand: "खोज बढ़ाएं",
    postJob: "नौकरी पोस्ट करें",
    myJobs: "मेरी नौकरियां",
    manageJobs: "अपनी नौकरियों का प्रबंधन करें",
    noJobs: "आपने अभी तक कोई नौकरी पोस्ट नहीं की है।",
    nearbyUsers: "आस-पास के उपयोगकर्ता",
    sort: "क्रमबद्ध करें",
    available: "उपलब्ध",
    busy: "व्यस्त",
    rented: "किराये पर",
    callFarmer: "किसान को कॉल करें",
    viewOnMap: "मानचित्र पर देखें",
    workType: "काम का प्रकार",
    dailyWage: "दैनिक मजदूरी",
    description: "विवरण",
    postJobBtn: "नौकरी पोस्ट करें",
    findJobs: "नौकरियां खोजें",
    iAmAvailable: "मैं उपलब्ध हूँ",
    notAvailable: "उपलब्ध नहीं हूँ",
    myFleet: "मेरे उपकरण",
    totalItems: "कुल आइटम",
    activeRentals: "सक्रिय किराये",
    manageEquip: "उपकरणों का प्रबंधन",
    aiMaintenance: "एआई रखरखाव",
    editDetails: "विवरण संपादित करें",
    addNewEquip: "नया उपकरण जोड़ें",
    equipName: "उपकरण का नाम",
    type: "प्रकार",
    manufacturer: "निर्माता",
    model: "मॉडल",
    year: "निर्माण का वर्ष",
    generatingImage: "छवि जनरेट हो रही है...",
    addAndGenerate: "जोड़ें और छवि जनरेट करें",
    maintenanceTips: "रखरखाव के सुझाव",
    gotIt: "समझ गया",
    welcomeBack: "वापस स्वागत है",
    createAccount: "खाता बनाएं",
    loginContinue: "जारी रखने के लिए लॉगिन करें",
    registeringAs: "पंजीकरण कर रहे हैं",
    fullName: "पूरा नाम",
    phoneNum: "फ़ोन नंबर",
    cityVillage: "शहर / गाँव",
    getOtp: "ओटीपी प्राप्त करें",
    verifyContinue: "सत्यापित करें और जारी रखें",
    changePhone: "फ़ोन नंबर बदलें",
    newUser: "नए उपयोगकर्ता?",
    signUpHere: "यहाँ साइन अप करें",
    alreadyAccount: "पहले से ही खाता है?",
    login: "लॉगिन करें",
    saveChanges: "बदलाव सहेजें",
    profileUpdated: "प्रोफ़ाइल अपडेट हो गई!",
    notifications: "सूचनाएं",
    noNotifications: "कोई नई सूचना नहीं",
    phoneNotRegistered: "फ़ोन नंबर पंजीकृत नहीं है",
    pleaseSignUpFirst: "कृपया पहले साइन अप करें",
    enterValidPhone: "कृपया एक वैध 10-अंकीय फ़ोन नंबर दर्ज करें",
    accountExists: "खाता पहले से मौजूद है। कृपया लॉगिन करें।"
  },
  Telugu: {
    welcome: "AgriConnect కు స్వాగతం",
    selectRole: "మీ పాత్రను ఎంచుకోండి",
    farmer: "రైతు",
    worker: "కూలీ",
    provider: "పరికరాల ప్రదాత",
    farmerDesc: "పనులు పోస్ట్ చేయండి మరియు పరికరాలను అద్దెకు తీసుకోండి.",
    workerDesc: "దగ్గర్లో ఉన్న పనులను కనుగొనండి.",
    providerDesc: "మీ యంత్రాలను అద్దెకు ఇవ్వండి.",
    detecting: "గుర్తిస్తోంది...",
    location: "ప్రాంతం",
    change: "మార్చు",
    workers: "కూలీలు",
    equipment: "యంత్రాలు",
    farmers: "రైతులు",
    nearest: "దగ్గరివి ముందు",
    rating: "మంచి రేటింగ్",
    km: "కి.మీ",
    call: "కాల్",
    book: "బుక్",
    perDay: "/రోజు",
    noResults: "ఫలితాలు లేవు. పరిధిని పెంచండి.",
    expand: "శోధన పెంచండి",
    postJob: "పనిని పోస్ట్ చేయండి",
    myJobs: "నా పనులు",
    manageJobs: "మీ పని పోస్టింగ్‌లను నిర్వహించండి",
    noJobs: "మీరు ఇంకా ఏ పనులను పోస్ట్ చేయలేదు.",
    nearbyUsers: "దగ్గరలో ఉన్న వినియోగదారులు",
    sort: "వరుస క్రమం",
    available: "అందుబాటులో ఉంది",
    busy: "బిజీగా ఉంది",
    rented: "అద్దెకు ఇవ్వబడింది",
    callFarmer: "రైతుకు కాల్ చేయండి",
    viewOnMap: "మ్యాప్‌లో చూడండి",
    workType: "పని రకం",
    dailyWage: "రోజువారీ కూలీ",
    description: "వివరణ",
    postJobBtn: "పనిని పోస్ట్ చేయి",
    findJobs: "పనులను కనుగొనండి",
    iAmAvailable: "నేను అందుబాటులో ఉన్నాను",
    notAvailable: "అందుబాటులో లేను",
    myFleet: "నా యంత్రాలు",
    totalItems: "మొత్తం పరికరాలు",
    activeRentals: "అద్దెకు ఉన్నవి",
    manageEquip: "పరికరాలను నిర్వహించండి",
    aiMaintenance: "AI నిర్వహణ",
    editDetails: "వివరాలను సవరించండి",
    addNewEquip: "కొత్త పరికరాన్ని జోడించండి",
    equipName: "పరికరం పేరు",
    type: "రకం",
    manufacturer: "తయారీదారు",
    model: "మోడల్",
    year: "తయారీ సంవత్సరం",
    generatingImage: "చిత్రాన్ని తయారు చేస్తోంది...",
    addAndGenerate: "జోడించి చిత్రాన్ని తయారు చేయి",
    maintenanceTips: "నిర్వహణ చిట్కాలు",
    gotIt: "సరే",
    welcomeBack: "స్వాగతం",
    createAccount: "ఖాతాను సృష్టించండి",
    loginContinue: "కొనసాగడానికి లాగిన్ చేయండి",
    registeringAs: "నమోదు చేసుకుంటున్నది",
    fullName: "పూర్తి పేరు",
    phoneNum: "ఫోన్ నంబర్",
    cityVillage: "నగరం / గ్రామం",
    getOtp: "OTP పొందండి",
    verifyContinue: "ధృవీకరించి కొనసాగండి",
    changePhone: "ఫోన్ నంబర్ మార్చండి",
    newUser: "కొత్త వినియోగదారులా?",
    signUpHere: "ఇక్కడ సైన్ అప్ చేయండి",
    // Fixed: Changed unquoted key with spaces to a consistent camelCase key 'alreadyAccount'
    alreadyAccount: "ఇప్పటికే ఖాతా ఉందా?",
    login: "లాగిన్",
    saveChanges: "మార్పులను సేవ్ చేయి",
    profileUpdated: "ప్రొఫైల్ నవీకరించబడింది!",
    notifications: "నోటిఫికేషన్‌లు",
    noNotifications: "కొత్త నోటిఫికేషన్‌లు లేవు",
    phoneNotRegistered: "ఫోన్ నంబర్ నమోదు చేయబడలేదు",
    pleaseSignUpFirst: "దయచేసి ముందుగా సైన్ అప్ చేయండి",
    enterValidPhone: "దయచేసి చెల్లుబాటు అయ్యే 10-అంకెల ఫోన్ నంబర్‌ను నమోదు చేయండి",
    accountExists: "ఖాతా ఇప్పటికే ఉంది. దయచేసి లాగిన్ చేయండి."
  },
  Spanish: {
    welcome: "Bienvenido a AgriConnect",
    selectRole: "Seleccione su rol",
    farmer: "Agricultor",
    worker: "Trabajador",
    provider: "Proveedor de Equipos",
    farmerDesc: "Publique trabajos, contrate trabajadores y alquile equipos.",
    workerDesc: "Encuentre trabajos cercanos y gane salarios.",
    providerDesc: "Alquile su maquinaria y gestione el inventario.",
    detecting: "Detectando...",
    location: "Ubicación",
    change: "Cambiar",
    workers: "Trabajadores",
    equipment: "Equipos",
    farmers: "Agricultores",
    nearest: "Más Cercano",
    rating: "Mejor Calificación",
    km: "km",
    call: "Llamar",
    book: "Reservar",
    perDay: "/día",
    noResults: "No hay resultados. Ampliar búsqueda.",
    expand: "Ampliar",
    postJob: "Publicar Trabajo",
    myJobs: "Mis Trabajos",
    manageJobs: "Gestionar sus publicaciones",
    noJobs: "Aún no ha publicado trabajos.",
    nearbyUsers: "Usuarios cercanos",
    sort: "Ordenar",
    available: "Disponible",
    busy: "Ocupado",
    rented: "Alquilado",
    callFarmer: "Llamar Agricultor",
    viewOnMap: "Ver en Mapa",
    workType: "Tipo de Trabajo",
    dailyWage: "Salario Diario",
    description: "Descripción",
    postJobBtn: "Publicar",
    findJobs: "Buscar Trabajos",
    iAmAvailable: "Estoy disponible",
    notAvailable: "No disponible",
    myFleet: "Mi Flota",
    totalItems: "Artículos totales",
    activeRentals: "Alquileres activos",
    manageEquip: "Gestionar equipos",
    aiMaintenance: "Mantenimiento AI",
    editDetails: "Editar detalles",
    addNewEquip: "Añadir equipo",
    equipName: "Nombre del equipo",
    type: "Tipo",
    manufacturer: "Fabricante",
    model: "Modelo",
    year: "Año de fabricación",
    generatingImage: "Generando imagen...",
    addAndGenerate: "Añadir y Generar",
    maintenanceTips: "Consejos de mantenimiento",
    gotIt: "Entendido",
    welcomeBack: "Bienvenido de nuevo",
    createAccount: "Crear cuenta",
    loginContinue: "Iniciar sesión para continuar",
    registeringAs: "Registrándose como",
    fullName: "Nombre completo",
    phoneNum: "Número de teléfono",
    cityVillage: "Ciudad / Pueblo",
    getOtp: "Obtener OTP",
    verifyContinue: "Verificar y continuar",
    changePhone: "Cambiar número",
    newUser: "¿Usuario nuevo?",
    signUpHere: "Regístrese aquí",
    alreadyAccount: "¿Ya tiene una cuenta?",
    login: "Iniciar sesión",
    saveChanges: "Guardar cambios",
    profileUpdated: "¡Perfil actualizado!",
    notifications: "Notificaciones",
    noNotifications: "No hay notificaciones",
    phoneNotRegistered: "Número de teléfono no registrado",
    pleaseSignUpFirst: "Por favor regístrese primero",
    enterValidPhone: "Por favor ingrese un número de teléfono válido de 10 dígitos",
    accountExists: "La cuenta ya existe. Por favor inicie sesión."
  }
};
